# Website metadata
title:          "Ateneo Mathematics Society"
email:          "contact@ateneomathsociety.org"
author:         "Matt E. Matics"
copyright:      ""
description:    "Ateneo Mathematics Society | Where Everybody Counts"
baseurl:        "/"
url:            "https://ateneomathsociety.github.io"
favicon:        "/assets/images/favicon.png"
content_width:  "920px"
sitemap:        false
debug:          false
facebook_url:   "https://www.facebook.com/AteneoMathematicsSociety"
twitter_url:    "https://x.com/AMSinfinitweet"

# Color settings
theme_color:        "#2E74BA"
brand_color:        "#ffffff"

# Website header
header_transparent: false
header_pages:
  - title:      "About"
    url:        "/about"
    dropdown:
      - title:  "Departments"
        url:    "/about/departments"
      - title:  "Offices"
        url:    "/about/offices"
      - title:  "Pools & Teams"
        url:    "/about/pools-teams"
  - title:      "Projects"
    url:        "/projects"
  - title:      "Services"
    url:        "/services"
  - title:      "Pages"
    url:        "/pages"
  - title:      "News"
    url:        "/news"

collections:
  departments:
    output:     true
    permalink:  "/about/departments/:slug"
  offices:
    output:     true
    permalink:  "/about/offices/:slug"
  pools_teams:
    output:     true
    permalink:  "/about/pools-teams/:slug"
  projects:
    output:     true
    permalink:  "/projects/:slug"
  services:
    output:     true
    permalink:  "/services/:slug"

defaults:
  - scope:
      path:     ""
      type:     "departments"
    values:
      layout:   "department"
  - scope:
      path:     ""
      type:     "offices"
    values:
      layout:   "office"
  - scope:
      path:     ""
      type:     "pools_teams"
    values:
      layout:   "pool_team"
  - scope:
      path:     ""
      type:     "projects"
    values:
      layout:   "project"
  - scope:
      path:     ""
      type:     "services"
    values:
      layout:   "service"

# Banner default settings
banner:
  image:            "/assets/images/banners/default.png"
  height:           180px
  min_height:       null
  opacity:          1.00
  background:       "#2E74BA"
  heading_style:    "font-weight: bold"
  subheading_style: "font-weight: bold"

# Blog settings
permalink:      "/news/:year-:month-:day/:title"
paginate:       5
yat:
  date_format:  "%b %d, %Y"

# Code badge setting
code_badge:
  enabled:            "true"
  color:              "#fff"
  background_color:   "#ff4e00"
  text_transform:     "uppercase"

# Photo previewer settings (PhotoSwipe 5), refer to: https://photoswipe.com/options/
photo_previewer:
  gallery:    "section.main"
  children:   "a.photo-swipe"
  bgOpacity:  0.8
  padding:
    top:      20
    bottom:   40
    left:     100
    right:    100

# Build settings
highlighter:  none
markdown:     kramdown
kramdown:
  input:      GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
